In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

# Creating Tensors

In [4]:
#Creating Tensors
# 1. Scalar Tensor

a=2
scalar=torch.tensor(42) #  creates a tensor containing a single value, 42
print("Scalar Tensor :", scalar)
print("Scalar Dimesion: ",scalar.ndim)
print("Scalar Shape: ",scalar.shape)

Scalar Tensor : tensor(42)
Scalar Dimesion:  0
Scalar Shape:  torch.Size([])


In [5]:
# 1d Tensor: vector

vector=torch.tensor([1,2,3,4,5])
print("vector Tensor :", vector)
print("vector Dimesion: ",vector.ndim)
print("vector Shape: ",vector.shape)

vector Tensor : tensor([1, 2, 3, 4, 5])
vector Dimesion:  1
vector Shape:  torch.Size([5])


In [6]:
#Matrix 2d

matrix=torch.tensor([[1,2,3],[4,5,6]])
print("Matrix Tensor :", matrix)
print("Matrix Dimesion: ",matrix.ndim)
print("Matrix Shape: ",matrix.shape)

Matrix Tensor : tensor([[1, 2, 3],
        [4, 5, 6]])
Matrix Dimesion:  2
Matrix Shape:  torch.Size([2, 3])


1D tensor → called a vector

2D tensor → called a matrix

More than 2D (3D, 4D, 5D, …) → generally called a tensor or higher-dimensional tensor

In [7]:
# 3d Tensor
#Matrix 2d

Tensor3d=torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
    ])
print(" Tensor :",Tensor3d )
print(" Dimesion: ",Tensor3d.ndim)
print(" Shape: ",Tensor3d.shape) # 2 matrices a 2*3

 Tensor : tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
 Dimesion:  3
 Shape:  torch.Size([2, 2, 3])


 the code then takes the vector tensor, which was defined earlier in the notebook, and moves it to the GPU memory using vector.to('cuda'). This creates gpu_tensor, which is now ready for GPU-accelerated computations.

In [8]:
#GPU Acceleration
if torch.cuda.is_available():
    gpu_tensor=vector.to('cuda')
    print("Tensor on GPU:",gpu_tensor)
else:
  print("Cuda is not available")

Tensor on GPU: tensor([1, 2, 3, 4, 5], device='cuda:0')


In [9]:
# Tensor Properties
print("Data type of matrix:",matrix.dtype)
print("Device tensor is stored on:",matrix.device)

Data type of matrix: torch.int64
Device tensor is stored on: cpu


In [10]:
# Tensor Properties
print("Data type of matrix:",vector.dtype)
print("Device tensor is stored on:",vector.device)

Data type of matrix: torch.int64
Device tensor is stored on: cpu


In [11]:
# Tensor Properties
print("Data type of matrix:",vector.dtype)
print("Device tensor is stored on:",gpu_tensor.device)

Data type of matrix: torch.int64
Device tensor is stored on: cuda:0


In [12]:
!nvidia-smi


Wed Dec 10 08:02:42 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P0             26W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [13]:
print("IS Tensor on cuda",matrix.is_cuda)


IS Tensor on cuda False


In [14]:
print(matrix.size())


torch.Size([2, 3])


In [15]:
print(matrix.numel()) # Give Num of elements

6


#Indexing and Slicing in Tensors

In [16]:
# Accessing Elements in Tensor

'''
tensor[row,column]
'''
import torch

In [22]:
tensor=torch.tensor([
    [10,20,30],[40,50,60],[70,80,90]
]

)

In [23]:
print(tensor.ndim)
print("shape",tensor.shape)

2
shape torch.Size([3, 3])


In [24]:
print("Element at (0,1):",tensor[0,1]) # 0th row and 1st column in 0th row

Element at (0,1): tensor(20)


In [25]:
print("Elements at (0th row):",tensor[0]) # 0th row and 1st column in 0th row

Elements at (0th row): tensor([10, 20, 30])


In [26]:
print("Element at (0 th column):",tensor[:,0]) # 0th row and 1st column in 0th row

Element at (0 th column): tensor([10, 40, 70])


In [27]:
print("Elements at (0th row):",tensor[0,:]) # 0th row and 1st column in 0th row

Elements at (0th row): tensor([10, 20, 30])


In [29]:
# Slicing

print("First two rows:\n",tensor[:2])

First two rows:
 tensor([[10, 20, 30],
        [40, 50, 60]])


In [30]:
# Slicing

print("First two cols:\n",tensor[:,:2])

First two cols:
 tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [31]:
# Slicing

print("in Row 1 we need 1 and 2 cols:\n",tensor[1,1:])

in Row 1 we need 1 and 2 cols:
 tensor([50, 60])


In [32]:
# Slicing

print("in Row 1 we need 1 and 2 cols:\n",tensor[1,1:3])

in Row 1 we need 1 and 2 cols:
 tensor([50, 60])


In [34]:
# Slicing

print("in Row 1 we need 1 and 2 cols:\n",tensor[1,3])

IndexError: index 3 is out of bounds for dimension 1 with size 3

In [35]:
# Fancy Indexing need (0,1)-->20 and (2,2)--> 90
tensor[[0,2],[1,2]] # [rows][cols] choose rows where elements are present and in cols in which columns it is present. in above (0,1),(2,2) from these rows in one and col in 1 20 is present 0  and 90 present at 2 rows [0,2] samesfrom the cols

tensor([20, 90])

In [37]:
#Boolean Indexing

tensor >=50

tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])

In [38]:
tensor[tensor>50]

tensor([60, 70, 80, 90])

In [40]:
# Changing Tensor Values via Indexing
print(tensor)
tensor[0,1]=25
print("After updating:\n",tensor)

tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])
After updating:
 tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [41]:
tensor[:,0]=torch.tensor([100,200,300]) #in all rows changing 0 th col

In [42]:
print(tensor)

tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [43]:
tensor[:,0]=torch.tensor([400,500]) #in all rows changing 0 th col

RuntimeError: The expanded size of the tensor (3) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [3].  Tensor sizes: [2]

Dim=0 --> rows
Dim=1 --> cols

In [44]:
indices=torch.tensor([0,2])
torch.index_select(tensor,dim=0,index=indices)

tensor([[100,  25,  30],
        [300,  80,  90]])

In [45]:
indices=torch.tensor([0,2])
torch.index_select(tensor,dim=1,index=indices)

tensor([[100,  30],
        [200,  60],
        [300,  90]])

In [47]:
#using Tensor with steps

print(tensor[:,::2]) # All rows and step 0f 2 we will get colums

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [50]:
tensor([2])

TypeError: 'Tensor' object is not callable

In [55]:
tensor=torch.tensor([
    [10,20,30,160,170],[40,50,60,180,190],[70,80,90,200,210],[100,110,120,220,230],[130,140,150,240,250]
]

)

In [57]:
print(tensor)

tensor([[ 10,  20,  30, 160, 170],
        [ 40,  50,  60, 180, 190],
        [ 70,  80,  90, 200, 210],
        [100, 110, 120, 220, 230],
        [130, 140, 150, 240, 250]])


In [56]:
#using Tensor with steps

print(tensor[:,::2]) # All rows and step 0f 2 we will get colums

tensor([[ 10,  30, 170],
        [ 40,  60, 190],
        [ 70,  90, 210],
        [100, 120, 230],
        [130, 150, 250]])


In [58]:
print(tensor[::-1]) # this works in numpy

ValueError: step must be greater than zero

In [60]:
print(tensor)

tensor([[ 10,  20,  30, 160, 170],
        [ 40,  50,  60, 180, 190],
        [ 70,  80,  90, 200, 210],
        [100, 110, 120, 220, 230],
        [130, 140, 150, 240, 250]])


In [59]:
torch.flip(tensor,dims=[1])

tensor([[170, 160,  30,  20,  10],
        [190, 180,  60,  50,  40],
        [210, 200,  90,  80,  70],
        [230, 220, 120, 110, 100],
        [250, 240, 150, 140, 130]])

In [61]:
torch.flip(tensor,dims=[0])

tensor([[130, 140, 150, 240, 250],
        [100, 110, 120, 220, 230],
        [ 70,  80,  90, 200, 210],
        [ 40,  50,  60, 180, 190],
        [ 10,  20,  30, 160, 170]])

In [62]:
torch.flip(tensor,dims=(0,))

tensor([[130, 140, 150, 240, 250],
        [100, 110, 120, 220, 230],
        [ 70,  80,  90, 200, 210],
        [ 40,  50,  60, 180, 190],
        [ 10,  20,  30, 160, 170]])

In [63]:
torch.flip(tensor,dims=(0,1)) # 1st flip row and then flip cols

tensor([[250, 240, 150, 140, 130],
        [230, 220, 120, 110, 100],
        [210, 200,  90,  80,  70],
        [190, 180,  60,  50,  40],
        [170, 160,  30,  20,  10]])

In [65]:
flip=torch.flip(tensor,dims=[0])
print(flip)

tensor([[130, 140, 150, 240, 250],
        [100, 110, 120, 220, 230],
        [ 70,  80,  90, 200, 210],
        [ 40,  50,  60, 180, 190],
        [ 10,  20,  30, 160, 170]])


In [66]:
torch.flip(flip,dims=[1])

tensor([[250, 240, 150, 140, 130],
        [230, 220, 120, 110, 100],
        [210, 200,  90,  80,  70],
        [190, 180,  60,  50,  40],
        [170, 160,  30,  20,  10]])