In [ ]:
import torch

In [ ]:
matrix= torch.tensor([
    [1.,2.,3.],
    [4,5,6],
    [7,8,9]
    ])

print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [ ]:
print(torch.sum(matrix, dim=1)) # Row wise sum

tensor([ 6., 15., 24.])


In [ ]:
print(torch.sum(matrix,dim=0)) # Col wise sum by default

tensor([12., 15., 18.])


In [ ]:
print(sum(matrix[0:]))

tensor([12., 15., 18.])


In [ ]:
print(matrix.sum())

tensor(45.)


In [ ]:
print(matrix.min())
print(matrix.max())

tensor(1.)
tensor(9.)


In [ ]:
print(matrix.mean())

tensor(5.)


In [ ]:
print(matrix.std())
print(matrix.median())


tensor(2.7386)
tensor(5.)


dim=0 --> rows
[0,1,2] but it will calculate oth column and 1 st column and 2nd column

Collapse rows, sum column-wise

dim=1--> Cols
it operates on rows

Collapse columns, sum row-wise

In [ ]:
print(matrix.min(dim=0))

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))


In [ ]:
print(matrix.max(dim=0))

torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))


In [ ]:
cum_sum=matrix.cumsum(dim=1) # it will do row wise sum by elemrnt wise 1st iteration 1 and 2nd iteration 1+2=3 and 3rd iteration 3+3=6 and there is no 4th column it will stop and go to next roe and start from iteration 1
print(cum_sum)

tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.],
        [ 7., 15., 24.]])


In [ ]:
cum_sum_col=matrix.cumsum(dim=0) # it will do col wise sum by elemrnt wise 1st iteration 1 and 2nd iteration 1+4=5 and 3rd iteration 5+7=12 and there is no 4th row it will stop and go to next col and start from iteration 1
print(cum_sum_col)

tensor([[ 1.,  2.,  3.],
        [ 5.,  7.,  9.],
        [12., 15., 18.]])


In [ ]:
cum_prod=matrix.cumprod(dim=1) #1st value is 1 and 1*2=2 and 2*3=6
print(cum_prod)

tensor([[  1.,   2.,   6.],
        [  4.,  20., 120.],
        [  7.,  56., 504.]])


In [ ]:
cum_prod_col=matrix.cumprod(dim=0) ##1st value is 1 and 1*4=4 and 4*7=28
print(cum_prod_col)

tensor([[  1.,   2.,   3.],
        [  4.,  10.,  18.],
        [ 28.,  80., 162.]])


# Advanced Aggregation

In [ ]:
print(matrix[matrix>5])
maskedmatrix_sum=matrix[matrix>5].sum()
print(maskedmatrix_sum)

tensor([6., 7., 8., 9.])
tensor(30.)


In [ ]:
non_zero=matrix.nonzero()
print(non_zero)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])


In [ ]:
print(non_zero.shape)

torch.Size([9, 2])


In [ ]:
print(non_zero.size(0))

9


In [ ]:
matrix_0= torch.tensor([
    [0,2,3.],
    [4,5,6],
    [7,8,9]
    ])

print(matrix_0)

tensor([[0., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [ ]:
zero=matrix_0.nonzero() # it is giving non zero index like 0th row and 1st col is non zero like that
print(zero)
print(zero.shape)
print(zero.size(0))

tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])
torch.Size([8, 2])
8


# Normalized Matrix

In [ ]:
max_v=matrix.max()
min_v=matrix.min()
normalized_matrix=(matrix-min_v)/(max_v-min_v)
print(normalized_matrix)

tensor([[0.0000, 0.1250, 0.2500],
        [0.3750, 0.5000, 0.6250],
        [0.7500, 0.8750, 1.0000]])


# View and Shape

view() and shape() are used to change the shape of the tensors. The core idea  is to transform a tensor into a new shape while keeping the data consistent.

view()  --> Works only if the tensor is stored contiguosly in memory

reshape() --> handle non contiguosly data also.
non contiguos tensor by creating a new tensor if needed.

rehape has more flexibility

view is constrained to use only the contiguos data.

Contigous

original_Data :[[1,2,3],[4,5,6]]

pytorch will store the data in sequential order(from left to right). It look like [1,2,3,4,5,6]  (5*5 grid like structure)

Non Contigous data: Transpose/slicing(Changing the tensor by some operations)

original_Data :[[1,2,3],[4,5,6]]

transposed_data: [[1,4],[2,5],[3,6]]

in memory it will stored as [1,2,3,4,5,6] even we changed the order sill it is stored as the above format.

The data is remains same in the memory, but the access pattern chnages  -- It is the issue. Now pytorch needs to perform indexing which is expensive

Perfomance is high in contiguous data. Non Contiguous data is low performance compared to contiguos data

In [34]:
"""
reshape gets the non contiguous data it wil create new copy which will come to rshpae and that data will be contiguos
if contigous data into reahpe it will just do the reshape

View only with contiguous data.. If u want make our system more strict towards our contiguos data, then we use this operation
"""

'\nreshape gets the non contiguous data it wil create new copy which will come to rshpae and that data will be contiguos\nif contigous data into reahpe it will just do the reshape\n\nView only with contiguous data.. If u want make our system more strict towards our contiguos data, then we use this operation\n'

In [35]:
import torch


In [37]:
tensor=torch.arange(12)
print(tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [38]:
reshaped_tensor_view=tensor.view(2,6)
print(reshaped_tensor_view)
print(reshaped_tensor_view.shape)

print("="*40)
reshaped_tensor_reshape=tensor.reshape(2,6)
print(reshaped_tensor_reshape)
print(reshaped_tensor_reshape.shape)


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])


In [39]:
tensor.is_contiguous()

True

In [40]:
# to check the contiguous or not

print(reshaped_tensor_view.is_contiguous())

print(reshaped_tensor_reshape.is_contiguous())

True
True


In [41]:
inferred_shape=tensor.view(3,-1) #-1 automatically pytorch will claculate the value based on number
print(inferred_shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [42]:
inferred_shape=tensor.view(-1,-1) #-1 automatically pytorch will claculate the value based on number
print(inferred_shape)

RuntimeError: only one dimension can be inferred

In [45]:
inferred_shape=tensor.view(-1,6) #-1 automatically pytorch will claculate the value based on number
print(inferred_shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [46]:
# m X n change to {1 X M}

tensor_3d=torch.arange(24).reshape(2,3,4)

In [47]:
print(tensor_3d)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [50]:
# convert to 1d tensor

flatten=tensor_3d.view(-1)
print(flatten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [51]:
flatten.is_contiguous()

True

In [52]:
tensor2d=torch.arange(24).reshape(12,2)
transpose_tensor=tensor2d.t()
print(transpose_tensor)

tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])


In [53]:
transpose_tensor.is_contiguous()

False

In [55]:
transpose_tensor.view(4,6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [58]:
error=transpose_tensor.reshape(4,6)
print(error)
print(error.shape)

tensor([[ 0,  2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11],
        [13, 15, 17, 19, 21, 23]])
torch.Size([4, 6])


In [59]:
contiguous=transpose_tensor.contiguous().view(4,6)
print(contiguous)
print(contiguous.shape)

tensor([[ 0,  2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11],
        [13, 15, 17, 19, 21, 23]])
torch.Size([4, 6])


# Stack Operation

combining the multiple tensor along a new dimension.

Tensor 1= 4 elements and Tensor 2 = 4 elements both tensor have dimension=1

if we need to get all the elements of dim=0 (accessing rows) dim=1 (accesing cols)

1*4 and 1*4 2 tensor total 8 elements

method1: along rows to do this we need to create new dimension (2,4)

tensor1
tensor2

method 2: along cols(4,2)

tensor1 tensor2

In [60]:
import torch

In [61]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])

print(tensor1)
print(tensor2)

print("="* 40)

print(tensor1.ndim)
print(tensor2.ndim)

print("="*40)

print(tensor1.size())
print(tensor2.size())


tensor([1, 2, 3])
tensor([4, 5, 6])
1
1
torch.Size([3])
torch.Size([3])


In [70]:
Row_stack=torch.stack([tensor1,tensor2],dim=0)
print(Row_stack)

print(Row_stack.ndim)

print(Row_stack.size())

tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])


In [71]:
Col_stack=torch.stack([tensor1,tensor2],dim=1)
print(Col_stack)

print(Col_stack.ndim)

print(Col_stack.ndim)

print(Row_stack.size())

tensor([[1, 4],
        [2, 5],
        [3, 6]])
2
2
torch.Size([2, 3])


In [65]:
tensor3=torch.tensor([7,8,9])
tensor4=torch.tensor([10,11,12])



In [68]:
Row_stack_new=torch.stack([tensor1,tensor2,tensor3,tensor4],dim=0)
print(Row_stack_new)

print(Row_stack_new.ndim)

print(Row_stack_new.size())

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
2
torch.Size([4, 3])


In [69]:
Col_stack_new=torch.stack([tensor1,tensor2,tensor3,tensor4],dim=1)
print(Col_stack_new)

print(Col_stack_new.ndim)

print(Col_stack_new.ndim)

print(Row_stack_new.size())

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])
2
2
torch.Size([4, 3])


In [73]:
# Stacking 2d Tensors

tensor_1=torch.tensor([[1,2,3],[4,5,6]])
tensor_2=torch.tensor([[7,8,9],[10,11,12]])
print(tensor_1.ndim)
print(tensor_2.ndim)
stacked_tensor_2d=torch.stack([tensor_1,tensor_2],dim=0)
print(stacked_tensor_2d)
print(stacked_tensor_2d.ndim)
print(stacked_tensor_2d.shape)
print(stacked_tensor_2d.numel())

2
2
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])
12


In [74]:
# Stacking 3d Tensors

tensor_1_3d=torch.tensor([[[1,2,3],[4,5,6],[13,14,15]]])
tensor_2_3d=torch.tensor([[[7,8,9],[10,11,12],[16,17,18]]])
print(tensor_1_3d.ndim)
print(tensor_2_3d.ndim)
print(tensor_1_3d.shape)
print(tensor_2_3d.shape)

stacked_tensor_3d=torch.stack([tensor_1_3d,tensor_2_3d],dim=0)
print(stacked_tensor_3d)
print(stacked_tensor_3d.ndim)
print(stacked_tensor_3d.shape) #[Batch , Channels , Height , Width]
print(stacked_tensor_3d.numel())

3
3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [13, 14, 15]]],


        [[[ 7,  8,  9],
          [10, 11, 12],
          [16, 17, 18]]]])
4
torch.Size([2, 1, 3, 3])
18


In [75]:
# Stacking 3d Tensors

tensor_1_3d=torch.tensor([[[1,2,3],[4,5,6],[13,14,15]]])
tensor_2_3d=torch.tensor([[[7,8,9],[10,11,12],[16,17,18]]])
print(tensor_1_3d.ndim)
print(tensor_2_3d.ndim)
print(tensor_1_3d.shape)
print(tensor_2_3d.shape)

stacked_tensor_3d=torch.stack([tensor_1_3d,tensor_2_3d],dim=1)
print(stacked_tensor_3d)
print(stacked_tensor_3d.ndim)
print(stacked_tensor_3d.shape) #[Batch , Channels , Height , Width]
print(stacked_tensor_3d.numel())

3
3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [13, 14, 15]],

         [[ 7,  8,  9],
          [10, 11, 12],
          [16, 17, 18]]]])
4
torch.Size([1, 2, 3, 3])
18


In [76]:
# Stacking 3d Tensors

tensor_1_3d=torch.tensor([[[1,2,3],[4,5,6],[13,14,15]]])
tensor_2_3d=torch.tensor([[[7,8,9],[10,11,12],[16,17,18]]])
print(tensor_1_3d.ndim)
print(tensor_2_3d.ndim)
print(tensor_1_3d.shape)
print(tensor_2_3d.shape)

stacked_tensor_3d=torch.stack([tensor_1_3d,tensor_2_3d],dim=2)
print(stacked_tensor_3d)
print(stacked_tensor_3d.ndim)
print(stacked_tensor_3d.shape) #[Batch , Channels , Height , Width]
print(stacked_tensor_3d.numel())

3
3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
tensor([[[[ 1,  2,  3],
          [ 7,  8,  9]],

         [[ 4,  5,  6],
          [10, 11, 12]],

         [[13, 14, 15],
          [16, 17, 18]]]])
4
torch.Size([1, 3, 2, 3])
18


In [77]:
# Stacking 3d Tensors

tensor_1_3d=torch.tensor([[[1,2,3],[4,5,6],[13,14,15]]])
tensor_2_3d=torch.tensor([[[7,8,9],[10,11,12],[16,17,18]]])
print(tensor_1_3d.ndim)
print(tensor_2_3d.ndim)
print(tensor_1_3d.shape)
print(tensor_2_3d.shape)

stacked_tensor_3d=torch.stack([tensor_1_3d,tensor_2_3d],dim=3)
print(stacked_tensor_3d)
print(stacked_tensor_3d.ndim)
print(stacked_tensor_3d.shape) #[Batch , Channels , Height , Width]
print(stacked_tensor_3d.numel())

3
3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
tensor([[[[ 1,  7],
          [ 2,  8],
          [ 3,  9]],

         [[ 4, 10],
          [ 5, 11],
          [ 6, 12]],

         [[13, 16],
          [14, 17],
          [15, 18]]]])
4
torch.Size([1, 3, 3, 2])
18


In [78]:
# Stacking 3d Tensors

tensor_1_3d=torch.tensor([[[1,2,3],[4,5,6],[13,14,15]]])
tensor_2_3d=torch.tensor([[[7,8,9],[10,11,12],[16,17,18]]])
print(tensor_1_3d.ndim)
print(tensor_2_3d.ndim)
print(tensor_1_3d.shape)
print(tensor_2_3d.shape)

stacked_tensor_3d=torch.stack([tensor_1_3d,tensor_2_3d],dim=4)
print(stacked_tensor_3d)
print(stacked_tensor_3d.ndim)
print(stacked_tensor_3d.shape) #[Batch , Channels , Height , Width]
print(stacked_tensor_3d.numel())

3
3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])


IndexError: Dimension out of range (expected to be in range of [-4, 3], but got 4)

In [83]:
# Stacking 2d Tensors

tensor_1_2d=torch.tensor([[1,2,3],[4,5,6],[13,14,15]])
tensor_2_2d=torch.tensor([[7,8,9],[10,11,12],[16,17,18]])
print(tensor_1_2d.ndim)
print(tensor_2_2d.ndim)
print(tensor_1_2d.shape)
print(tensor_2_2d.shape)
print("="*40)
stacked_tensor_2d=torch.stack([tensor_1_2d,tensor_2_2d],dim=0)
print(stacked_tensor_2d)
print(stacked_tensor_2d.ndim)
print(stacked_tensor_2d.shape) #[Batch , Channels , Height , Width]
print(stacked_tensor_2d.numel())

2
2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [16, 17, 18]]])
3
torch.Size([2, 3, 3])
18


In [82]:
# Stacking 2d Tensors

tensor_1_2d=torch.tensor([[1,2,3],[4,5,6],[13,14,15]])
tensor_2_2d=torch.tensor([[7,8,9],[10,11,12],[16,17,18]])
print(tensor_1_2d.ndim)
print(tensor_2_2d.ndim)
print(tensor_1_2d.shape)
print(tensor_2_2d.shape)
print("="*40)
stacked_tensor_2d=torch.stack([tensor_1_2d,tensor_2_2d],dim=1)
print(stacked_tensor_2d)
print(stacked_tensor_2d.ndim)
print(stacked_tensor_2d.shape) #[Batch , Channels , Height , Width]
print(stacked_tensor_2d.numel())

2
2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
3
torch.Size([3, 2, 3])
18


In [84]:
# Stacking 2d Tensors

tensor_1_2d=torch.tensor([[1,2,3],[4,5,6],[13,14,15]])
tensor_2_2d=torch.tensor([[7,8,9],[10,11,12],[16,17,18]])
print(tensor_1_2d.ndim)
print(tensor_2_2d.ndim)
print(tensor_1_2d.shape)
print(tensor_2_2d.shape)
print("="*40)
stacked_tensor_2d=torch.stack([tensor_1_2d,tensor_2_2d],dim=2)
print(stacked_tensor_2d)
print(stacked_tensor_2d.ndim)
print(stacked_tensor_2d.shape) #[Batch , Channels , Height , Width]
print(stacked_tensor_2d.numel())

2
2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]],

        [[13, 16],
         [14, 17],
         [15, 18]]])
3
torch.Size([3, 3, 2])
18


 [1,2] dim=0 --> [] dim1 --> access elements  

 if dim=0  we will get  the same tensor

 dim=0 row wise tensor all rows combined together

 dim=1 col wise tensor we will combine dtogether

[[1,2]] dim=0 --> [1,2] dim=1  all the elements 1,2  and dim=2 col1 and col2

#Concatenation


In [93]:
# COncatenation
print(torch.cat((tensor1,tensor2),dim=0))
print(torch.cat((tensor1,tensor2),dim=0).shape)
print(torch.cat((tensor1,tensor2),dim=0).ndim)
# print(torch.cat((tensor1,tensor2),dim=1))

tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])
1


In [97]:
print(torch.cat((tensor_1_2d,tensor_2_2d),dim=0))
print(torch.cat((tensor_1_2d,tensor_2_2d),dim=0).shape)
print(torch.cat((tensor_1_2d,tensor_2_2d),dim=0).ndim)

print(torch.cat((tensor_1_2d,tensor_2_2d),dim=1))
print(torch.cat((tensor_1_2d,tensor_2_2d),dim=1).shape)
print(torch.cat((tensor_1_2d,tensor_2_2d),dim=1).ndim)

# print(torch.cat((tensor_1_2d,tensor_2_2d),dim=2))





tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [13, 14, 15],
        [ 7,  8,  9],
        [10, 11, 12],
        [16, 17, 18]])
torch.Size([6, 3])
2
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]])
torch.Size([3, 6])
2


In [100]:
print(torch.cat((tensor_1_3d,tensor_2_3d),dim=0))
print(torch.cat((tensor_1_3d,tensor_2_3d),dim=0).shape)
print(torch.cat((tensor_1_3d,tensor_2_3d),dim=0).ndim)

print("="*20)

print(torch.cat((tensor_1_3d,tensor_2_3d),dim=1))
print(torch.cat((tensor_1_3d,tensor_2_3d),dim=1).shape)
print(torch.cat((tensor_1_3d,tensor_2_3d),dim=1).ndim)

print("="*20)

print(torch.cat((tensor_1_3d,tensor_2_3d),dim=2))
print(torch.cat((tensor_1_3d,tensor_2_3d),dim=2).shape)
print(torch.cat((tensor_1_3d,tensor_2_3d),dim=2).ndim)

print("="*20)

# print(torch.cat((tensor_1_3d,tensor_2_3d),dim=3))

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [16, 17, 18]]])
torch.Size([2, 3, 3])
3
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [ 7,  8,  9],
         [10, 11, 12],
         [16, 17, 18]]])
torch.Size([1, 6, 3])
3
tensor([[[ 1,  2,  3,  7,  8,  9],
         [ 4,  5,  6, 10, 11, 12],
         [13, 14, 15, 16, 17, 18]]])
torch.Size([1, 3, 6])
3
