# Multiclass Classification with pytorch using custom NN

In [3]:
from sklearn.datasets import load_iris
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score


In [4]:
iris=load_iris()

In [7]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['target']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [9]:
df['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [10]:
train_df,test_df=train_test_split(df,test_size=0.2,random_state=42)

In [12]:
train_df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
22                 4.6               3.6  ...               0.2       0
15                 5.7               4.4  ...               0.4       0
65                 6.7               3.1  ...               1.4       1
11                 4.8               3.4  ...               0.2       0
42                 4.4               3.2  ...               0.2       0
..                 ...               ...  ...               ...     ...
71                 6.1               2.8  ...               1.3       1
106                4.9               2.5  ...               1.7       2
14                 5.8               4.0  ...               0.2       0
92                 5.8               2.6  ...               1.2       1
102                7.1               3.0  ...               2.1       2

[120 rows x 5 columns]

In [14]:
X_train=train_df.drop('target',axis=1)
y_train=train_df['target']
X_test=test_df.drop('target',axis=1)
y_test=test_df['target']

# X_train,y_train=train_df.drop(column=['target']),train_df['target']

In [15]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
dtype: object

In [17]:
df.select_dtypes(include='object').columns

Index([], dtype='object')

In [18]:
df.shape

(150, 5)

In [23]:
df.select_dtypes(exclude='object').columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [24]:
# Standard Scalar
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [26]:
print(X_train)

[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]
 [ 0.59831066 -1.25582892  0.72969227  0.95664273]
 [ 0.72020757  0.30929911  0.44316389  0.4227026 ]
 [-0.74255534  0.98006827 -1.27600637 -1.31260282]
 [-0.98634915  1.20365799 -1.33331205 -1.31260282]
 [-0.74255534  2.32160658 -1.27600637 -1.44608785]
 [-0.01117388 -0.80864948  0.78699794  0.95664273]
 [ 0.23261993  0.75647855  0.44316389  0.55618763]
 [ 1.08589829  0.08570939  0.55777524  0.4227026 ]
 [-0.49876152  1.87442714 -1.39061772 -1.04563275]
 [-0.49876152  1.4272477  -1.27600637 -1.31260282]
 [-0.37686461 -1.47941864 -0.01528151 -0.24472256]
 [ 0.59831066 -0.58505976  0.78699794  0.4227026 ]
 [ 0.72020757  0.08570939  1.01622064  0.8231577 ]
 [ 0.96400139 -0.13788033  0.38585821  0.28921757]
 [ 1.69538284  1.20365799  1.36

In [27]:
print(y_train)

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: target, Length: 120, dtype: int64


In [28]:
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train.values,dtype=torch.long)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.long)

#torch.long is a data type (dtype) in PyTorch.
# It means 64-bit integer (int64).

In [43]:
class IRIS_Multiclass(nn.Module):
  def __init__(self,input_dim,hidden_dim,output_dim):
    super(IRIS_Multiclass,self).__init__()
    self.network = nn.Sequential(
        nn.Linear(input_dim,hidden_dim),
        nn.ReLU(),
        nn.Linear(hidden_dim,hidden_dim),
        nn.ReLU(),
        nn.Linear(hidden_dim,output_dim)
    )
  def forward(self,X):
    return self.network(X)

In [57]:
input_dim=X_train.shape[1]
hidden_dim=16
output_dim=3

In [71]:
model=IRIS_Multiclass(input_dim,hidden_dim,output_dim)
print(model)

IRIS_Multiclass(
  (network): Sequential(
    (0): Linear(in_features=4, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=16, bias=True)
    (3): ReLU()
    (4): Linear(in_features=16, out_features=3, bias=True)
  )
)


In [72]:
torch.manual_seed(42)
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(),lr=0.01)

In [73]:
# Train the Model Training



epochs=500
for epoch in range(epochs):
  # print(epoch
  optimizer.zero_grad()
  model.train()

  predictyhat=model(X_train_tensor)
  loss=criterion(predictyhat,y_train_tensor)
  loss.backward()
  optimizer.step()

  if (epoch+1)%100==0:
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}')

Epoch 100/500, Loss: 0.0411
Epoch 200/500, Loss: 0.0182
Epoch 300/500, Loss: 0.0027
Epoch 400/500, Loss: 0.0009
Epoch 500/500, Loss: 0.0005


In [76]:
#Evaluation

model.eval()

with torch.no_grad(): #we dont wnat to perform any updatwe
  y_pred=model(X_test_tensor)
  y_pred_label=torch.argmax(y_pred,dim=1)
  accuracy=accuracy_score(y_test_tensor,y_pred_label)
  print(f'Accuracy: {accuracy:.4f}')
  print(confusion_matrix(y_test_tensor,y_pred_label))
  print(classification_report(y_test_tensor,y_pred_label))

  # roc_auc=roc_auc_score(y_test_tensor,y_pred.numpy(),multi_class='ovr')

Accuracy: 1.0000
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [78]:
accuracy= (y_pred_label==y_test_tensor).sum().item()/y_test_tensor.size(0)

In [79]:
print(accuracy)

1.0


In [80]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [95]:
def predict_iris(sepal_length,sepal_width,petal_length,petal_width):
  input_data=np.array([[sepal_length,sepal_width,petal_length,petal_width]])
  # input_data=scaler.transform(input_data.reshape(1,-1))
  input_data=scaler.transform(input_data)
  input_data=torch.tensor(input_data,dtype=torch.float32)
  model.eval()
  with torch.no_grad():
    prediction=model(input_data)
    prediction_class=torch.argmax(prediction,dim=1).item()
    print(prediction_class)
    return iris.target_names[prediction_class]


In [96]:
prediction_class=predict_iris(5.1,3.5,1.4,0.2)
print(f"Predicted_Species : {prediction_class}")

0
Predicted_Species : setosa


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
