# Tensor Manipulation

It refers to operation that alters the structure,shape or content of tensors.

- Reshaping
- Slicing
- Joining or Splitting
- Transposing and permutting dimension

In [ ]:

import torch

In [ ]:
#Reshaping Tensors
#reshape
#view

original_tensor=torch.arange(12)
print(original_tensor)
print(original_tensor.nelement())
print(original_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


In [ ]:
#Reshape the tensor
reshape_tensor=original_tensor.reshape(3,4)
print(reshape_tensor)
print(reshape_tensor.nelement())
print(reshape_tensor.ndim)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
12
2


View is also same but internally it requires a contiguous memory. This is the only diff b/w reshape and view.

In RAM, In our memory all the data points should be in a sequence.

In [ ]:
# View # -1 -- refers to dimension it will automatically calculated by your pytorch.

original_tensor.view(-1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
reshape_tensor.view(-1
                    )

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
original_tensor.is_contiguous()

True

In [ ]:
reshape_tensor.is_contiguous()

True

In [ ]:
# original_tensor=torch.arange(12)
unsequence=reshape_tensor.flip(dims=(0,1))
print(unsequence)
print(unsequence.is_contiguous())

tensor([[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]])
True


In [ ]:
reshape_tensor[0,1]=25

In [ ]:
print(reshape_tensor)
print(reshape_tensor.is_contiguous())

tensor([[ 0, 25,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
True


In [ ]:
# is contigious whether it is stored in the sequence in memory or not.

## Slicing
Extract specific portions of tensors

In [ ]:
tensor_a=torch.tensor([
    [1,2,3],[4,5,6],[7,8,9]
    ])

In [ ]:
tensor_a.ndim

2

In [ ]:
print(tensor_a[0])

tensor([1, 2, 3])


In [ ]:
print(tensor_a[:,0])

tensor([1, 4, 7])


In [ ]:
print(tensor_a.shape)

torch.Size([3, 3])


In [ ]:
sub_tensor=tensor_a[1:,1:]
print(sub_tensor)
print(sub_tensor.shape)
print(sub_tensor.ndim)

tensor([[5, 6],
        [8, 9]])
torch.Size([2, 2])
2


#Joining Tensors

In [41]:
# torch.cat()  --> merges tensors along an existing dimension
tensor1=torch.tensor([[1,2],[3,4]])
tensor2=torch.tensor([[5,6],[7,8]])

concat_tensor_rows=torch.cat((tensor1,tensor2),dim=0)
concat_tensor_cols=torch.cat((tensor1,tensor2),dim=1)

print("Tensor1:\n ",tensor1)
print("Tensor2:\n ",tensor2)
print("="*20)
print("Concat Tensor Rows:\n ",concat_tensor_rows)
print("="*20)
print("Concat Tensor Cols:\n ",concat_tensor_cols)


Tensor1:
  tensor([[1, 2],
        [3, 4]])
Tensor2:
  tensor([[5, 6],
        [7, 8]])
Concat Tensor Rows:
  tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Concat Tensor Cols:
  tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [42]:
print(concat_tensor_rows.shape)
print(concat_tensor_cols.shape)

torch.Size([4, 2])
torch.Size([2, 4])


In [44]:
# Stack  --> create a new dimension, increases the tensor's rank
print(tensor1.shape)
print(tensor2.shape)

print("="*20)
print(concat_tensor_rows.shape)
print(concat_tensor_cols.shape)
print("="*20)

stack_concat_tensor_rows=torch.stack((tensor1,tensor2),dim=0)
stack_concat_tensor_cols=torch.stack((tensor1,tensor2),dim=1)

print("Stack Concat Tensor Rows:\n ",stack_concat_tensor_rows)
print("Stack Concat Tensor Cols:\n ",stack_concat_tensor_cols)

print("="*20)
print(stack_concat_tensor_rows.shape)
print(stack_concat_tensor_cols.shape)


torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([4, 2])
torch.Size([2, 4])
Stack Concat Tensor Rows:
  tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Stack Concat Tensor Cols:
  tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])


# Splitting tensors

- torch.chunk() --> divides your tensor int equal-sized chunks
- torch.split() --> allows uneven splitting based on size

In [45]:
# torch.chunk

origin_tensor=torch.arange(12)

chunks=torch.chunk(origin_tensor,3,dim=0)

print(chunks)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]))


In [46]:
# torch.chunk

origin_tensor=torch.arange(15)

chunks=torch.chunk(origin_tensor,5,dim=0)

print(chunks)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]), tensor([12, 13, 14]))


In [47]:
for chunk in chunks:
  print(chunk)

tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])
tensor([12, 13, 14])


In [53]:
# torch.chunk

origin_tensor=torch.arange(16)

chunks=torch.chunk(origin_tensor,5,dim=0)

for chunk in chunks:
  print(chunk)

tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([ 8,  9, 10, 11])
tensor([12, 13, 14, 15])


In [50]:
# torch.split

splits=torch.split(origin_tensor,5,dim=0)

for split in splits:
  print(split)

tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11])


In [ ]:
# split will decide how many values are inside the tensor 15/5=3 values in each chunk total 5 chunks if we have 16 values we need to divide by 5 which will be uneven so it will do interanlly arange in 4 chunks chunk shouldbe even
#chunk will decides how many chunks are requied 12(numbers)/5 chunks 2 split with 5 values and 1 split will be 2 values

In [54]:
# torch.split

splits=torch.split(origin_tensor,7,dim=0)

for split in splits:
  print(split)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([ 7,  8,  9, 10, 11, 12, 13])
tensor([14, 15])


# Transposing and premuting

- transpose() --> swaps 2 dimension.  m * n --> n * m
- premute() --> rearrange all dimension in the specified order

In [55]:
tensor_original=torch.arange(24).reshape(12,2)

In [56]:
print(tensor_original)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])


In [57]:
transpose=tensor_original.transpose(0,1) #This operation swaps the 0th and 1st dimensions of the tensor, effectively reorienting it.
print(transpose)

tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])


In [58]:
tensor_matrix=torch.arange(24).reshape(2,3,4)
print(2*3*4)

24


In [62]:
torch.arange(25).reshape(2,3,5) # we must check the reshape index values is equal to the tensor_matrix  without reahape torch.arange(24)

RuntimeError: shape '[2, 3, 5]' is invalid for input of size 25

In [63]:
tensor_original=torch.arange(24).reshape(2,3,4)# need 2 tensor and each tensor should be 3*4
print(tensor_original)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


[0,1,2]  this is the order

[2,0,1] whatever the index 0 is swapped b/w 2 and 1 with 0 and index 2 is replaced with 1


In [64]:
premute_tensor=tensor_original.permute(2,0,1)
print(premute_tensor)

tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])


In [67]:
print(tensor_original.shape)

"""2 is replaced with 4
   3 is replaced with 2
   4 is replaced with 3
   as we mentioned 0 index is swapped with index 2 and index 1 is swapped with index 0 and index 2 is swapped with index 1"""
print(premute_tensor.shape)

torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [69]:
import copy
a = [[1, 2], [3, 4]]
b = copy.copy(a)   # or a[:] or list(a)
print("a",a)
print("b",b)

a [[1, 2], [3, 4]]
b [[1, 2], [3, 4]]


In [70]:
b[0][0] = 99

In [71]:
print("a",a)
print("b",b)


a [[99, 2], [3, 4]]
b [[99, 2], [3, 4]]


In [72]:
c = copy.deepcopy(a)
print(c)

[[99, 2], [3, 4]]


In [73]:
print(a)

[[99, 2], [3, 4]]


In [74]:
c[0][0]=100

In [75]:
print(c)
print(a)

[[100, 2], [3, 4]]
[[99, 2], [3, 4]]


# Cloning and detaching



In [76]:
tensor=torch.ones(3,3,requires_grad=True) # part of computation graph

In [77]:
clone_tensor=tensor.clone()  # part of computation graph
 # It will be a part of the gradient and will have a new memory reference. But when u mention tensor.detach this particular tensor will come out of our computation graph. it will be new tensor. it will share the same storage as the original one. only differnece

In [78]:
print(tensor)
print(clone_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], grad_fn=<CloneBackward0>)


In [ ]:
detached_tensor=tensor.deatach() # This code will detach the tensor from the computation graph
# not a part of computation graph
#but storage will be same as the original ones