# Understanding pytorch NN components

In [ ]:
'''
breakdown of a  simple NN

x--> I/P
wx--> Weights
bx-- Bias
A --> Activation function
Y-- O/P

z = w1.x+b
a = A(z)  # applying the activation function
Y= w2. a + b2


# Loss Function

# Back propogation

# optimizer

'''

'\nbreakdown of a  simple NN\n\nx--> I/P\nwx--> Weights\nbx-- Bias\nA --> Activation function\nY-- O/P\n\nz = w1.x+b\na = A(z)  # applying the activation function\nY= w2. a + b2\n\n\n# Loss Function\n\n# Back propogation\n\n# optimizer\n\n'


## Components of Pytorch

- Base class for defining customer models : torch.nn.Module
- Fully connected (dense) layers : torch.nn.Linear
- Activation function : torch.nn.ReLU
- optimiser : torch.optim
- Loss Function : torch.nn.CrossEntropyLoss
- Loads the data in batch : torch.utils.data.DataLoader

## Different ways to create NN

1. Functional : Flexible,but little harder to interpret

2. Sequential : More structured/stacking in Linear Order (nn.Sequential)

## Building a Neural Network

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

You are creating your own neural network class called SimpleNN.

It inherits from nn.Module.

nn.Module is the base class for all neural network models in PyTorch.

Because of this, your model gets all the required functions (like .parameters(), .cuda(), .train(), etc.)

def __init__(self, input_size, hidden_size, output_size):

This is the constructor of your class.

It runs when you create the model.

It calls the constructor of nn.Module.

It initializes the parent class.

Without this, your model won’t work.

A constructor is a special function inside a class that runs automatically when you create an object of that class.

model = SimpleNN(10, 20, 2)
It will run when you write this automatically __init__ will start executing

super(SimpleNN,self).__init__()

Run nn.Module.__init__(self).

self refers to the current object (your neural network model instance).

self refers to model

It is the SAME self that you use everywhere inside the class.


Class = Blueprint of a house

Object = Actual house built from the blueprint

You can build many houses from the same blueprint.

model = SimpleNN(10, 20, 2)

model is the object

self inside the class refers to model

So:

self.fc1 becomes model.fc1

self.fc2 becomes model.fc2

self.relu becomes model.relu

def __init__(self, input_size, hidden_size, output_size):
The word self is how you access the object being created.
Without self, the object cannot store anything.

fc1 = nn.Linear(...)
❌ PyTorch will NOT save it
❌ It will NOT become part of the model
❌ It will NOT be trained


self.fc1 = nn.Linear(...)
means:

store fc1 inside the object

so later you can use object.fc1

In [ ]:
## Functional API

# must inherit the base class nn.Module in pytorch

class SimpleNN(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super(SimpleNN,self).__init__()
    self.fc1 = nn.Linear(input_size,hidden_size)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size,output_size)
  def forward(self,X): # X and Input size should be same
      x = self.fc1(X)
      x= self.relu(x)
      x= self.fc2(x)
      return x

      # Functional we change the flow
      """
      x = self.fc1(X)
      x= self.relu(x)
      y= self.fc2(x)
      y= self.relu(y)
      return y

      PyTorch only recognizes forward() — if you misspell it, your model won’t work!
      """

In [ ]:
## Sequnraial API

# must inherit the base class nn.Module in pytorch

class SimpleNNSequential(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super(SimpleNN,self).__init__()
    self.network=nn.Sequential(
        nn.Linear(input_size,hidden_size),
        nn.ReLU(),
        nn.Linear(hidden_size,output_size)
    )

    def forward(self,X): # X and Input size should be same
      y = self.network(X)
      return y


  # sequential : it will run sequentially we cannot chnage the flow of your n/w here. But in this functional we change the flow how we can navigate in foward after y u can add activation function then get the o/p

In ResNet we cannot use sequential because the input will be used along o/p of hidden layer 1 and hidden layer1  o/p will be used as i/p along with hidden layer2 o/p to another layer.
In this case we can use functionl

self.fc1=

self.fc2
slef.fc3=self.fc1+self.fc2+self.fc3

# Training the NN

In [ ]:
model_func=SimpleNN(input_size=4,hidden_size=8,output_size=3) #o/p size=3 we will get answer 0/1/2(softmax) we have 3 labels
print(model_func)

SimpleNN(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=8, out_features=3, bias=True)
)


In [ ]:
print(model_func.parameters)

<bound method Module.parameters of SimpleNN(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=8, out_features=3, bias=True)
)>


In [ ]:
X=torch.rand(10,4)
print(X)

tensor([[0.7564, 0.9913, 0.2225, 0.4372],
        [0.0978, 0.3020, 0.0051, 0.9698],
        [0.0279, 0.4112, 0.4455, 0.0906],
        [0.4168, 0.1722, 0.3329, 0.3416],
        [0.9695, 0.8929, 0.6331, 0.4895],
        [0.8422, 0.7363, 0.2163, 0.2054],
        [0.6517, 0.4807, 0.4390, 0.6297],
        [0.7096, 0.0386, 0.7678, 0.3809],
        [0.9732, 0.8142, 0.1648, 0.1203],
        [0.9349, 0.0370, 0.0025, 0.9670]])


In [ ]:
Y=torch.randint(0,3,(10,)) # o/p sizwe is 3 so the o/p value willbe b/w 0 to 3
print(Y)

tensor([2, 1, 1, 0, 0, 0, 1, 2, 0, 1])


In [ ]:
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model_func.parameters(),lr=0.01)

In [ ]:
# Training Loop

epoch =120
for e in range(epoch):
  optimizer.zero_grad() # To clear all the gradients
  output=model_func(X)
  loss=criterion(output,Y) # Calculate Loss
  loss.backward() # Calculate Gradients
  optimizer.step() # Update the weights

  if (e+1)%10==0: #every 10 epoch we need to print
    print(f'Epoch: [{e+1}]/50, Loss: {loss.item():.4f}')


Epoch: [10]/50, Loss: 0.5728
Epoch: [20]/50, Loss: 0.4959
Epoch: [30]/50, Loss: 0.4317
Epoch: [40]/50, Loss: 0.3792
Epoch: [50]/50, Loss: 0.3355
Epoch: [60]/50, Loss: 0.2988
Epoch: [70]/50, Loss: 0.2673
Epoch: [80]/50, Loss: 0.2400
Epoch: [90]/50, Loss: 0.2164
Epoch: [100]/50, Loss: 0.1956
Epoch: [110]/50, Loss: 0.1774
Epoch: [120]/50, Loss: 0.1612


In [ ]:
# Training Loop

epoch =120
for e in range(epoch):
  optimizer.zero_grad() # To clear all the gradients
  output=model_func(X)
  loss=criterion(output,Y) # Calculate Loss
  loss.backward() # Calculate Gradients
  optimizer.step() # Update the weights

  if (e+1)%10==0: #every 10 epoch we need to print
    print(f'Epoch: [{e+1}]/50, Loss: {loss.item():.4f}')


Epoch: [10]/50, Loss: 1.0442
Epoch: [20]/50, Loss: 0.9905
Epoch: [30]/50, Loss: 0.9199
Epoch: [40]/50, Loss: 0.8387
Epoch: [50]/50, Loss: 0.7525
Epoch: [60]/50, Loss: 0.6794
Epoch: [70]/50, Loss: 0.6188
Epoch: [80]/50, Loss: 0.5700
Epoch: [90]/50, Loss: 0.5311
Epoch: [100]/50, Loss: 0.4993
Epoch: [110]/50, Loss: 0.4725
Epoch: [120]/50, Loss: 0.4509


# 2

# Create Linear Regression Model with Pytorch components

1. Data Gathering
2. Data Preprocessing
3. Feature Engineering
4. Model Training
5. Testing

In [ ]:
! pip install kaggle

In [ ]:
import kagglehub

# Download the latest version
path=kagglehub.dataset_download("mirichoi0218/insurance")
print(f"Path of Datset files: {path}")

Using Colab cache for faster access to the 'insurance' dataset.
Path of Datset files: /kaggle/input/insurance


In [ ]:
import os
print(os.getcwd())

/content


In [ ]:
os.listdir("/kaggle/input/insurance")

['insurance.csv']

In [ ]:
import pandas as pd


In [ ]:
df=pd.read_csv(os.path.join(path,"insurance.csv"))
print(df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [ ]:
df.shape

(1338, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [ ]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=1338, step=1)

In [ ]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [ ]:
df.values

array([[19, 'female', 27.9, ..., 'yes', 'southwest', 16884.924],
       [18, 'male', 33.77, ..., 'no', 'southeast', 1725.5523],
       [28, 'male', 33.0, ..., 'no', 'southeast', 4449.462],
       ...,
       [18, 'female', 36.85, ..., 'no', 'southeast', 1629.8335],
       [21, 'female', 25.8, ..., 'no', 'southwest', 2007.945],
       [61, 'female', 29.07, ..., 'yes', 'northwest', 29141.3603]],
      dtype=object)

In [ ]:
df.ndim

2

In [ ]:
df.size #Total number of elements
# above all these call as Attributes

9366

In [ ]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
df.describe(include="all")

age   sex          bmi     children smoker     region  \
count   1338.000000  1338  1338.000000  1338.000000   1338       1338   
unique          NaN     2          NaN          NaN      2          4   
top             NaN  male          NaN          NaN     no  southeast   
freq            NaN   676          NaN          NaN   1064        364   
mean      39.207025   NaN    30.663397     1.094918    NaN        NaN   
std       14.049960   NaN     6.098187     1.205493    NaN        NaN   
min       18.000000   NaN    15.960000     0.000000    NaN        NaN   
25%       27.000000   NaN    26.296250     0.000000    NaN        NaN   
50%       39.000000   NaN    30.400000     1.000000    NaN        NaN   
75%       51.000000   NaN    34.693750     2.000000    NaN        NaN   
max       64.000000   NaN    53.130000     5.000000    NaN        NaN   

             charges  
count    1338.000000  
unique           NaN  
top              NaN  
freq             NaN  
mean    13270.422265  
std     12110.011237  
min      1121.873900  
25%      4740.287150  
50%      9382.033000  
75%     16639.912515  
max     63770.428010

In [ ]:
# Methods
print("describe",df.describe())
print("="*20)
print("Describe all",df.describe(include="all"))
print("="*20)
print("Head",df.head())
print("="*20)
print("Tail",df.tail())
print("="*20)
print(df.info)


describe                age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010
Describe all                 age   sex          bmi     children smoker     region  \
count   1338.000000  1338  1338.000000  1338.000000   1338       1338   
unique          NaN     2          NaN          NaN      2          4   
top             NaN  male          NaN          NaN     no  southeast   
freq            NaN   676          NaN          NaN   1064        364   
mean      39.207025   NaN    30.663397     1.094918    NaN        NaN   
std      

In [ ]:
df[['smoker']].value_counts()

smoker
no        1064
yes        274
Name: count, dtype: int64

In [ ]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [ ]:
df[['smoker']].values

array([['yes'],
       ['no'],
       ['no'],
       ...,
       ['no'],
       ['no'],
       ['yes']], dtype=object)

In [ ]:
df[['smoker']].nunique()

smoker    2
dtype: int64

In [ ]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split


In [ ]:
# Split dataset before encoding

train_df,test_df=train_test_split(df,test_size=0.2,random_state=42)
print(train_df)

      age     sex     bmi  children smoker     region      charges
560    46  female  19.950         2     no  northwest   9193.83850
1285   47  female  24.320         0     no  northeast   8534.67180
1142   52  female  24.860         0     no  southeast  27117.99378
969    39  female  34.320         5     no  southeast   8596.82780
486    54  female  21.470         3     no  northwest  12475.35130
...   ...     ...     ...       ...    ...        ...          ...
1095   18  female  31.350         4     no  northeast   4561.18850
1130   39  female  23.870         5     no  southeast   8582.30230
1294   58    male  25.175         0     no  northeast  11931.12525
860    37  female  47.600         2    yes  southwest  46113.51100
1126   55    male  29.900         0     no  southwest  10214.63600

[1070 rows x 7 columns]


In [ ]:
df.dtypes == 'object'


age         False
sex          True
bmi         False
children    False
smoker       True
region       True
charges     False
dtype: bool

In [ ]:
df.dtypes[df.dtypes == 'object']

sex       object
smoker    object
region    object
dtype: object

In [ ]:
df.select_dtypes(include=['object', 'category']).columns

Index(['sex', 'smoker', 'region'], dtype='object')

In [ ]:
# Encode categorical variables
label_encoder={}
for col in df.select_dtypes(include=['object', 'category']).columns:
  le=LabelEncoder()
  train_df[col]=le.fit_transform(train_df[col])
  test_df[col]=le.transform(test_df[col])
  label_encoder[col]=le

In [ ]:
print(label_encoder)

{'sex': LabelEncoder(), 'smoker': LabelEncoder(), 'region': LabelEncoder()}


In [ ]:
print(train_df)

      age  sex     bmi  children  smoker  region      charges
560    46    0  19.950         2       0       1   9193.83850
1285   47    0  24.320         0       0       0   8534.67180
1142   52    0  24.860         0       0       2  27117.99378
969    39    0  34.320         5       0       2   8596.82780
486    54    0  21.470         3       0       1  12475.35130
...   ...  ...     ...       ...     ...     ...          ...
1095   18    0  31.350         4       0       0   4561.18850
1130   39    0  23.870         5       0       2   8582.30230
1294   58    1  25.175         0       0       0  11931.12525
860    37    0  47.600         2       1       3  46113.51100
1126   55    1  29.900         0       0       3  10214.63600

[1070 rows x 7 columns]


In [ ]:
# Features and Target

X_train=train_df.drop('charges',axis=1) # train_df.drop(columns=['charges'])
y_train=train_df['charges']

X_test=test_df.drop('charges',axis=1) # test_df.drop(columns=['charges'])
y_test=test_df['charges']

In [ ]:
print(X_train.head())

      age  sex    bmi  children  smoker  region
560    46    0  19.95         2       0       1
1285   47    0  24.32         0       0       0
1142   52    0  24.86         0       0       2
969    39    0  34.32         5       0       2
486    54    0  21.47         3       0       1


In [ ]:
print(y_train.head())

560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
Name: charges, dtype: float64


fit_transform=
The encoder must learn categories

Then apply transformation

transform

Because test data must not influence training.
Then the encoder will learn from test, which is WRONG.

It may create a different mapping, causing mismatches.

In [ ]:
# Normalize featrures
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


In [ ]:
print(X_train)

[[ 0.47222651 -1.0246016  -1.75652513  0.73433626 -0.50874702 -0.45611589]
 [ 0.54331294 -1.0246016  -1.03308239 -0.91119211 -0.50874702 -1.35325561]
 [ 0.8987451  -1.0246016  -0.94368672 -0.91119211 -0.50874702  0.44102382]
 ...
 [ 1.3252637   0.97598911 -0.89153925 -0.91119211 -0.50874702 -1.35325561]
 [-0.16755139 -1.0246016   2.82086429  0.73433626  1.96561348  1.33816354]
 [ 1.1120044   0.97598911 -0.10932713 -0.91119211 -0.50874702  1.33816354]]


In [ ]:
y_test.values

array([ 9095.06825 ,  5272.1758  , 29330.98315 ,  9301.89355 ,
       33750.2918  ,  4536.259   ,  2117.33885 , 14210.53595 ,
        3732.6251  , 10264.4421  , 18259.216   ,  7256.7231  ,
        3947.4131  , 46151.1245  , 48673.5588  , 44202.6536  ,
        9800.8882  , 42969.8527  ,  8233.0975  , 21774.32215 ,
        5080.096   ,  7441.501   ,  1256.299   ,  2755.02095 ,
       11085.5868  , 10923.9332  , 12644.589   , 18804.7524  ,
        9715.841   ,  1131.5066  , 15828.82173 , 11842.62375 ,
        2020.5523  ,  5693.4305  ,  2904.088   ,  7448.40395 ,
        2597.779   ,  7337.748   , 23887.6627  , 38709.176   ,
        4687.797   ,  2643.2685  , 11674.13    , 12124.9924  ,
        4889.9995  , 12333.828   ,  3579.8287  ,  4391.652   ,
       42124.5153  ,  4463.2051  , 13887.204   ,  1719.4363  ,
       28476.73499 ,  1708.92575 , 10594.2257  , 25333.33284 ,
        3645.0894  , 38746.3551  , 11848.141   , 10564.8845  ,
       13880.949   ,  4753.6368  , 27941.28758 ,  8017.

In [113]:
y_train

560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
           ...     
1095     4561.18850
1130     8582.30230
1294    11931.12525
860     46113.51100
1126    10214.63600
Name: charges, Length: 1070, dtype: float64

In [ ]:
y_test

764      9095.06825
887      5272.17580
890     29330.98315
1293     9301.89355
259     33750.29180
           ...     
109     47055.53210
575     12222.89830
535      6067.12675
543     63770.42801
846      9872.70100
Name: charges, Length: 268, dtype: float64

In [118]:
y_train.shape # !d dimension

(1070,)

In [119]:
yy=torch.tensor(y_train, dtype=torch.float32).view(-1,1)
yy.shape # convert to 2d dimension
#view(-1) will change dimesion 1D

torch.Size([1070, 1])

In [121]:
# Convert into Tensor

X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train.values,dtype=torch.float32).view(-1,1) # y_train the data will be in pandas. y_train.values only we are getting values
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.float32).view(-1,1)

#

In [123]:
print(y_test_tensor.shape)

torch.Size([268, 1])


In [125]:
print(X_test_tensor.shape)

torch.Size([268, 6])


In [126]:
# Define NN

class SimpleNNRegresionModel(nn.Module):
  def __init__(self,input_dim):
    super(SimpleNNRegresionModel,self).__init__()
    self.network= nn.Sequential(
        nn.Linear(input_dim,64),
        nn.ReLU(),
        nn.Linear(64,128),
        nn.ReLU(),
        nn.Linear(128,1)
    )

  def forward(self,X):
    return self.network(X)

In [127]:
input_dim=X_train_tensor.shape[1]

model=SimpleNNRegresionModel(input_dim)

In [128]:
print(model)

SimpleNNRegresionModel(
  (network): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=1, bias=True)
  )
)


In [130]:
# Loss and optimization

criterion=nn.MSELoss()
optimizer=optim.Adam(model.parameters(),lr=0.01)

In [151]:
# Training loop
epochs=40000
for epoch in range(epochs):
  model.train()
  optimizer.zero_grad()
  output=model(X_train_tensor)
  loss=criterion(output,y_train_tensor)
  loss.backward()
  optimizer.step()

  if (epoch+1)%10000==0:
    print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')


Epoch [10000/40000], Loss: 1838703.2500
Epoch [20000/40000], Loss: 1642991.5000
Epoch [30000/40000], Loss: 1790790.8750
Epoch [40000/40000], Loss: 1492808.3750


model.train()
🔹 Put the model in training mode
Enables dropout (if present)

Enables batch normalization updates (if present)

Good practice always before training step

 optimizer.zero_grad()
🔹 Reset gradients to 0
Gradients accumulate in PyTorch, so you must clear old gradients before computing new ones.

 output = model(X_train_tensor)
🔹 Forward pass
Input: X_train_tensor
Output: model prediction (ŷ)
This runs the forward() method of the model.

 loss = criterion(output, y_train_tensor)
🔹 Calculate loss
Checks how far prediction is from actual:

Loss = MSE( ŷ , y )

Lower loss = better model.

 loss.backward()
🔹 Backpropagation
Computes gradients of loss with respect to all model weights.

PyTorch stores them in:
weight.grad

optimizer.step()
🔹 Update weights
Uses gradients to move weights in direction that reduces loss.


Equivalent to:

weight = weight - learning_rate * gradient


But done automatically by Adam optimizer.

loss.item()
gives:

Copy code
0.12345
🔹 Converts tensor → Python float
🔹 Makes it printable, loggable, usable in normal Python code

In [152]:
# Model Evaluation

model.eval()
y_pred=model(X_test_tensor).detach().numpy()


In [153]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

mse=mean_squared_error(y_test_tensor.numpy(),y_pred)
mae=mean_absolute_error(y_test_tensor.numpy(),y_pred)
r2=r2_score(y_test_tensor.numpy(),y_pred)

print(f"MSE : {mse:.2f}")
print(f"MAE : {mae:.2f}")
print(f"R2 : {r2:.2f}")

MSE : 65254416.00
MAE : 5327.94
R2 : 0.58


In [154]:
def predict_charges(age,sex,bmi,children,smoker,region):
  input_data=pd.DataFrame([[age,sex,bmi,children,smoker,region]],columns=['age','sex','bmi','children','smoker','region'])
  # input_data['sex']=label_encoder['sex'].transform(input_dim_
  for col in ['sex','smoker','region']:
    input_data[col]=label_encoder[col].transform(input_data[col])

  input_data=scaler.transform(input_data)
  input_tensor=torch.tensor(input_data,dtype=torch.float32)
  with torch.no_grad():
    model.eval()
    prediction=model(input_tensor).item()
  return prediction

  # predicted_charge=model(input_tensor).item()
  # return predicted_charge

predicted_charges=predict_charges(19,'female',27.9,0,'yes','southeast')
print(f"Predicted Insurance Charges : ${predicted_charges}")
#



Predicted Insurance Charges : $21896.259765625


In [150]:
def predict_charges(age,sex,bmi,children,smoker,region):
  input_data=pd.DataFrame([[age,sex,bmi,children,smoker,region]],columns=['age','sex','bmi','children','smoker','region'])
  # input_data['sex']=label_encoder['sex'].transform(input_dim_
  for col in ['sex','smoker','region']:
    input_data[col]=label_encoder[col].transform(input_data[col])

  input_data=scaler.transform(input_data)
  input_tensor=torch.tensor(input_data,dtype=torch.float32)
  # with torch.no_grad():
  #   model.eval()
  #   prediction=model(input_tensor).item()
  # return prediction

  predicted_charge=model(input_tensor).item()
  return predicted_charge

predicted_charges=predict_charges(19,'female',27.9,0,'yes','southeast')
print(f"Predicted Insurance Charges : ${predicted_charges}")
#



Predicted Insurance Charges : $20497.73828125


In [140]:
filtered_df = df[(df['age'] == 19) & (df['sex'] == 'female') &(df['bmi']==27.9)]
print(filtered_df)

   age     sex   bmi  children smoker     region    charges
0   19  female  27.9         0    yes  southwest  16884.924
